# Change these first
owner: ksvblog
repo: stats

sites:
  - name: HHK (Short B/Vlogs)
    url: https://hhk.my.id
  - name: K's V/Blog (Old)
    url: https://ksvblog.site
  - name: K's V/Blog (Cloudflare)
    url: https://ksvblog.pages.dev
  - name: K's V/Blog (Github)
    url: https://ksvblog.github.io
  - name: K's V/Blog (Netlify)
    url: https://ksvblog.netlify.app
  - name: K's V/Blog (Netlify)
    url: https://ksvblog.netlify.app
  - name: Benchmark
    url: https://speedlify.hhk.my.id
  - name: Upptime
    url: https://stats.hhk.my.id

status-website:
  cname: stats.hhk.my.id
  favicon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/upptime-icon.svg
  logoUrl: https://raw.githubusercontent.com/ksvblog/stats/master/assets/upptime-icon.svg
  name: Stats
  introTitle: "**Upptime** stats pages for K's V/Blog. :)"
  introMessage: Welcome to our website! We're up and running, ready to provide you with valuable statistics and insights. Explore with confidence!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://hhk.my.id
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
