# Change these first
owner: hhkmy
repo: stats

sites:
  - name: HHK (Short B/Vlogs)
    url: https://hhk.my.id
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/HHK_KSVBlog.svg
  - name: K's V/Blog (Cloudflare)
    url: https://ksvblog.pages.dev
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/HHK_KSVBlog.svg
  - name: K's V/Blog (Github)
    url: https://ksvblog.github.io
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/HHK_KSVBlog.svg
  - name: K's V/Blog (Netlify)
    url: https://ksvblog.netlify.app
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/HHK_KSVBlog.svg
  - name: K's V/Blog (Netlify)
    url: https://ksvblog.netlify.app
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/HHK_KSVBlog.svg
  - name: Benchmark
    url: https://speedlify.hhk.my.id
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/Speedlify.svg
  - name: Upptime
    url: https://stats.hhk.my.id
    icon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/upptime-icon.svg

status-website:
  cname: stats.hhk.my.id
  favicon: https://raw.githubusercontent.com/ksvblog/stats/master/assets/upptime-icon.svg
  logoUrl: https://raw.githubusercontent.com/ksvblog/stats/master/assets/upptime-icon.svg
  name: Up and Down
  introTitle: "**Up and Down** stats pages for K's V/Blog :)"
  introMessage: Welcome to our website! We're up and running, ready to provide you with valuable statistics and insights. Explore with confidence!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://hhk.my.id
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
