# Change these first
owner: ksvblog
repo: stats

sites:
  - name: K's V/Blog
    url: https://ksvblog.site
  - name: K's V/Blog (Cloudflare)
    url: https://ksvblog.pages.dev
  - name: K's V/Blog (Github)
    url: https://ksvblog.github.io
  - name: K's V/Blog (Netlify)
    url: https://ksvblog.netlify.app

status-website:
  cname: stats.ksvblog.site
  favicon: https://raw.githubusercontent.com/h2kyaw/stats/master/assets/logo.svg
  logoUrl: https://raw.githubusercontent.com/h2kyaw/stats/master/assets/logo.svg
  name: Stats
  introTitle: "**Upptime** stats pages for K's V/Blog. :)"
  introMessage: Welcome to our website! We're up and running, ready to provide you with valuable statistics and insights. Explore with confidence!
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://ksvblog.site
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
